colorScheme = "congo"

enableCodeCopy = true
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true


[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true
  recentLimit = 5

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[article]
  showDraftLabel = true
  showTaxonomies = true
  showTableOfContents = true
  showHeadingAnchors = true
  sharingLinks = ["facebook", "twitter", "reddit", "linkedin", "email"]

[taxonomy]
  showTermCount = true
