apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-15
spec:
  instances: 3

  storage:
    size: 1Gi

  managed:
    roles:
      - name: app
        login: true
        replication: true
